backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_library:
  name: cloudinary
  config:
    cloud_name: dypxaqdgb
    api_key: 339985235411373
    multiple: true

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "src/pages/index.md"
        label: "Página Home"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: HeroImage, name: heroImage, widget: image}
          - {label: HeroHeading, name: heroHeading, widget: string}
          - {label: HeroSubHeading, name: heroSubHeading, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: CaroueselImages, name: carouselImages, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}


      - file: "src/pages/about/index.md"
        label: "Página quienes somos"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: HeroImage, name: heroImage, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/camper-vans/index.md"
        label: "Pagina de Camper vans"
        name: "camper-vans"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "camper-vans-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: HeroImage, name: heroImage, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/prices/index.md"
        label: "Página de precios"
        name: "prices"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "price-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: HeroImage, name: heroImage, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/conditions/index.md"
        label: "Página de condiciones"
        name: "conditions"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "condition-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: HeroImage, name: heroImage, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/FAQ/index.md"
        label: "Página de FAQ"
        name: "FAQ"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "FAQ-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: HeroImage, name: heroImage, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Questions, name: questions, widget: list, fields: [{label: Question, name: question, widget: string}, {label: Answer, name: answer, widget: string}]}
          - {label: "Body", name: "body", widget: "markdown"}


      - file: "src/pages/contact/index.md"
        label: "Página de Contacto"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pricing"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "camper-vans"
    label: "Camper vans"
    folder: "src/pages/camper-vans"
    create: true
    path: "{{year}}-{{month}}-{{slug}}/index"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "camper-van-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: image}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Equipment", name: "equipment", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: Image, name: image, widget: image}
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    media_folder: '/images'
    public_folder: '/images'
    path: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
